<a href="https://colab.research.google.com/github/ganeshgaiy/MNIST-digit-classification---NN/blob/main/MNIST.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install torchshow

In [ ]:
import torch
import torchshow as ts

In [ ]:
scalar = torch.tensor(8)

In [ ]:
scalar.ndim

0

In [ ]:
vector = torch.tensor([7,8])

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
vector.ndim

1

In [ ]:
tnsr = torch.tensor([[[7,8,3],[8,9,3],[1,2,3]]])

In [ ]:
tnsr.ndim

3

In [ ]:
tnsr.shape

torch.Size([1, 3, 3])

tnsr is a 2 dimensional tensor with 2 columns

In [ ]:
tnsr1 = torch.tensor([[[0,0],[9,10],[11,12],[13,14]]])

In [ ]:
tnsr1

tensor([[[ 0,  0],
         [ 9, 10],
         [11, 12],
         [13, 14]]])

In [ ]:
tnsr1.ndim

3

In [ ]:
tnsr1.shape

torch.Size([1, 4, 2])

In [ ]:
torch.rand(1,4,2)

tensor([[[0.3070, 0.0809],
         [0.6897, 0.6298],
         [0.8354, 0.3676],
         [0.1127, 0.8343]]])

In [ ]:
torch.zeros(1,2,3)

tensor([[[0., 0., 0.],
         [0., 0., 0.]]])

In [ ]:
torch.ones(1,2,3)

tensor([[[1., 1., 1.],
         [1., 1., 1.]]])

In [ ]:
X = torch.arange(1,10)

In [ ]:
X.ndim

1

In [ ]:
X.shape

torch.Size([9])

In [ ]:
torch.zeros(10)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
X.device

device(type='cpu')

In [ ]:
tnsr1+10

tensor([[[10, 10],
         [19, 20],
         [21, 22],
         [23, 24]]])

In [ ]:
X.type(torch.float32)

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
X.min()

tensor(1)

In [ ]:
X.max()

tensor(9)

In [ ]:
X.sum()

tensor(45)

In [ ]:
X.type(torch.float32).mean()

tensor(5.)

In [ ]:
X.shape

torch.Size([9])

In [ ]:
X.reshape(1,9)

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
from collections import Counter

In [ ]:
x = [1,1,1,3,2,31,3,1,4]

In [ ]:
max(Counter(x).values())

4

In [ ]:
[2]*2


[2, 2]

In [ ]:
tnsr1[0][1][1]

tensor(10)

In [ ]:
torch.ones_like(tnsr1[0])

tensor([[1, 1],
        [1, 1],
        [1, 1],
        [1, 1]])

In [ ]:
y=torch.tensor([[[1,2],[2,2]]])
y.shape

torch.Size([1, 2, 2])

In [ ]:
from torch.utils.data import Dataset
from pathlib import Path

label_mapping = {
    'class1': 0,
    'class2': 1,
    'class3': 2
}

class customImageDataSet(Dataset):
  def __init__(self, rootdir):
    self.images = list(Path(rootdir).glob('*/*/*.jpg'))

  def __len__(self):
    return len(self.images)

  def __getitem__(self,idx):
    image = self.images[idx]
    label = label_mapping.get(image.parent.name)
    return image, label

In [ ]:
from torchvision import datasets
from torchvision.transforms import ToTensor

device = (
    "cuda" if torch.cuda.is_available() else "mps" if torch.backends.mps.is_available() else "cpu"
)

print(device)

cuda


In [ ]:
training_data = datasets.FashionMNIST(
    root="data",
    train=True,
    download=True,
    transform=ToTensor()
)

In [ ]:
test_data = datasets.FashionMNIST(
    root="data",
    train = False,
    download=True,
    transform=ToTensor()
)

In [ ]:
labels_map = {
    0: "T-Shirt",
    1: "Trouser",
    2: "Pullover",
    3: "Dress",
    4: "Coat",
    5: "Sandal",
    6: "Shirt",
    7: "Sneaker",
    8: "Bag",
    9: "Ankle Boot",
}

In [ ]:
from torch.utils.data import DataLoader

train_dataloader = DataLoader(training_data, batch_size=64, shuffle=True)
test_dataloader = DataLoader(test_data, batch_size=64, shuffle=True)

#how to take a sample from dataloader

x, y = next(iter(test_dataloader))

In [ ]:
from torch import nn

print(nn.Flatten(x))

Flatten(
  start_dim=tensor([[[[0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
            [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
            [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
            ...,
            [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
            [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
            [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000]]],
  
  
          [[[0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
            [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
            [0.0000, 0.0000, 0.0039,  ..., 0.0078, 0.0000, 0.0000],
            ...,
            [0.0000, 0.0000, 0.0039,  ..., 0.0078, 0.0000, 0.0000],
            [0.0000, 0.0000, 0.0000,  ..., 0.0039, 0.0000, 0.0000],
            [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000]]],
  
  
          [[[0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
            [0.0000, 0.0000, 0.0000,  ..., 0.00

In [ ]:
from torch import nn

class NeuralNetwork(nn.Module):
  def __init__(self):
    self.flatten = nn.Flatten()
    self.linear_relu_stack = nn.Sequential(
        nn.Linear(28*28, 32),
        nn.Relu(),
        nn.Linear(32,16),
        nn.Relu(),
        nn.Linear(16,10)
    )

  def forward(self, x):
    x = self.flatten(x)
    logits = self.linear_relu_stack(x)
    return logits


In [ ]:
#1. Imports
import torch
from torch import nn
from torchvision import datasets
import torchvision.transforms as transforms
from torch.utils.data import DataLoader
import torch.optim as optim

#2. Device Configuration
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

print(device)
#3. Hyperparameters
learning_rate = 0.001
num_epochs = 5
batch_size = 100

#4. Data Augmentation and normalization for training
transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.2860), (0.3530))
])

#5. Load datasets
train_data = datasets.FashionMNIST(
    root='data',
    train=True,
    download=True,
    transform=transform,
)

test_data = datasets.FashionMNIST(
    root='data',
    train=False,
    download=True,
    transform=transform
)

train_loader = DataLoader(train_data, batch_size=batch_size, shuffle=True)
test_loader = DataLoader(test_data, batch_size=batch_size, shuffle=False)

#6. Define a neural network
class NeuralNetwork(nn.Module):
  def __init__(self):
    super(NeuralNetwork, self).__init__()
    self.layer1 = nn.Linear(28*28, 128)
    self.layer2 = nn.Linear(128, 64)
    self.layer3 = nn.Linear(64,10)

  def forward(self, x):
    x = x.view(-1, 28*28) #x.shape: (batch_size,1,28*28) -> (batch_size, 28*28). -1 infers to batch_size
    x = torch.relu(self.layer1(x))
    x = torch.relu(self.layer2(x))
    x = self.layer3(x)
    return x

model = NeuralNetwork().to(device)

#7. Loss and optimizer
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=learning_rate)

#8. Training the model
total_steps = len(train_loader)
for epoch in range(num_epochs):
  for i, (images, labels) in enumerate(train_loader):
    images = images.to(device)
    labels =  labels.to(device)

    #forward pass
    outputs = model(images)
    loss = criterion(outputs, labels)

    #backpropagation and optimize
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if (i+1)%100 == 0:
      print(f"Epoch [{epoch+1}/{num_epochs}], step [{i+1}/{total_steps}], Loss: {loss.item():.4f}")

#9. Testing the model
# predictions and labels
model.eval()
with torch.no_grad():
  correct = 0
  total = 0
  for images, labels in test_loader:
    images, labels = images.to(device), labels.to(device)
    outcomes = model(images)
    _, predicted = torch.max(outcomes.data, 1)
    total+=labels.size(0)
    correct += (predicted==labels).sum().item()

  print(f"Test accuracy on the model of {total} test images is {(correct/total)*100:.2f}%")


#10. Training accuracy
model.train()
with torch.no_grad():
  correct = 0
  total = 0
  for images, labels in train_loader:
    images, labels = images.to(device), labels.to(device)
    outcomes = model(images)
    _, predicted = torch.max(outcomes.data, 1)
    total+=labels.size(0)
    correct += (predicted==labels).sum().item()
    print('correct', correct)
  print(f"Test accuracy on the model of {total} training images is {(correct/total)*100}%")









cuda
Epoch [1/5], step [100/600], Loss: 0.6482
Epoch [1/5], step [200/600], Loss: 0.4483
Epoch [1/5], step [300/600], Loss: 0.4600
Epoch [1/5], step [400/600], Loss: 0.4673
Epoch [1/5], step [500/600], Loss: 0.3474
Epoch [1/5], step [600/600], Loss: 0.4743
Epoch [2/5], step [100/600], Loss: 0.2789
Epoch [2/5], step [200/600], Loss: 0.3023
Epoch [2/5], step [300/600], Loss: 0.3817
Epoch [2/5], step [400/600], Loss: 0.3279
Epoch [2/5], step [500/600], Loss: 0.3581
Epoch [2/5], step [600/600], Loss: 0.3155
Epoch [3/5], step [100/600], Loss: 0.3439
Epoch [3/5], step [200/600], Loss: 0.4383
Epoch [3/5], step [300/600], Loss: 0.3552
Epoch [3/5], step [400/600], Loss: 0.3432
Epoch [3/5], step [500/600], Loss: 0.3063
Epoch [3/5], step [600/600], Loss: 0.4700
Epoch [4/5], step [100/600], Loss: 0.3464
Epoch [4/5], step [200/600], Loss: 0.2860
Epoch [4/5], step [300/600], Loss: 0.2992
Epoch [4/5], step [400/600], Loss: 0.1963
Epoch [4/5], step [500/600], Loss: 0.2673
Epoch [4/5], step [600/600], 

In [ ]:
x,y=next(iter(test_loader))

In [ ]:
y.size(0)